### ISSUE TITLE
Implement the All Client Register

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-hf#16]
![Picture2](https://user-images.githubusercontent.com/20777928/61236326-696ce300-a740-11e9-9bbc-4a60f276d909.png)

- [x] All clients with a referral or in another register (i.e. ANC, Malaria, PNC, Family Planning) will appear in this register
- [x] Top left menu button opens side menu (#502 )
- [x] Swiping from the left also opens side menu (#502)
- [x] Dynamic search bar (https://github.com/OpenSRP/opensrp-client-chw/issues/492)
- [ ] Due only toggle (https://github.com/OpenSRP/opensrp-client-chw/issues/517)
- [x] Row text display (https://github.com/OpenSRP/opensrp-client-chw/issues/516)
- [x] Client row arrow takes you to the client's profile

**Comment by msschroeder** [comment]
QA Build October 18:
- lgtm except for unchecked
- Will wait to close until finished

**Comment by msschroeder** [comment]
Closing and leaving the filter open
