### ISSUE TITLE
Implement Malaria Register

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-hf#20]
<img width="379" alt="Picture3" src="https://user-images.githubusercontent.com/20777928/61239203-1185aa80-a747-11e9-81b4-34f5a4f68cee.png">

- [x] All clients in the Malaria register will appear in this register.
- [x] Top left menu button opens side menu (#502  )
- [x] Swiping from the left also opens side menu (#502 )
- [x] Dynamic search bar (#544 )
- [x] Due only toggle (#519 )
- [x] Row text display - first line: {first_name} {middle_name} {surname}, {age} - Taken from the Registration information.
- [x] Row text display - second line: {sex} {fam_village} - Taken from Registration Info.
- [ ] Row text display - third line: (if the client has a referral): Referral [number of days since referral is given] days ago - This should be red text with a light red background as shown in the screen shot above with Susan as an example.
- [x] Client row arrow takes you to the client's profile

**Comment by msschroeder** [comment]
QA Oct 18 Build:
@ellykits lgtm, except for the last check. I will wait to close until finished

**Comment by Mstjamush** [comment]
Issues 

1. The toggle (top rightI indicated "Referred" instead of "Due only"
2. In scenarios where a client is in PNC/ANC, the gender is not displayed but PNC/ANC (clarity required)
