### ISSUE TITLE
Implement Remove Family Member action

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-hf#21]
Same as the [CHW All Families Register](https://github.com/OpenSRP/opensrp-client-chw/issues/28). I have copied the issue here for simplicity.

Marvel link: https://marvelapp.com/9j1277a/screen/49183723

<img width="378" alt="screen shot 2018-12-05 at 10 15 57 pm" src="https://user-images.githubusercontent.com/1584163/49559069-60c74b00-f8db-11e8-8c26-3397f27e333a.png">

- [ ] Tapping on the Remove existing family member button in the top-right drop down icon in the family profile page opens this screen (https://marvelapp.com/9j1277a/screen/48411529)
- [ ] All family members are listed, from oldest to youngest (i.e. mockup is not the correct order)
- [ ] Family head and primary caregiver roles are displayed below the member, as shown above. The two roles can be the same person or different people.
- [ ] First name, middle name, last name, and age are shown on the first line, then gender is shown on the second line
- [ ] Tapping the right arrow launches the remove member form for that family member (https://github.com/OpenSRP/opensrp-client-chw-hf/issues/17)
- [ ] The remove entire family option shows number of adults and number of children in the family
- [ ] If an entire family is removed, all family member records are automatically archived as well; otherwise, if just a single family member is removed, only that member is archived, and the family record remains
- [ ] If you select the family head or primary caregiver family member, before you can remove that person you first need to select a new family head and/or primary caregiver (https://github.com/OpenSRP/opensrp-client-chw-hf/issues/18)
- [ ] Quick note on displaying age. For children's ages, I created an issue on this (https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/18), so for displaying ages above for children, use "d" for days, "w" for weeks, "m" for months, and "y" for years. For adults (not U5 child), just show the number, you don't have to show the years.
