### ISSUE TITLE
Implement PNC register

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-hf#21]
<img width="379" alt="Picture3" src="https://user-images.githubusercontent.com/20777928/61238920-5bba5c00-a746-11e9-82de-693866a2764d.png">

- [x] All clients in the PNC register will appear in this register.
- [x] Top left menu button opens side menu (#502  )
- [x] Swiping from the left also opens side menu (#502 )
- [x] Dynamic search bar (#544 )
- [x] Due only toggle (#519 )
- [x] Row text display - first line: {first_name} {middle_name} {surname}, {age} - Taken from the Registration information.
- [x] Row text display - second line: PNC day [{today} -{delivery_date}] {fam_village} - Taken from Registration Info and ANC registration information
- [x] Row text display - third line: (if the client has a referral): Referral [number of days since referral is given] days ago - This should be red text with a light red background as shown in the screen shot above with Susan as an example.
- [x] Client row arrow takes you to the client's profile

**Comment by msschroeder** [comment]
lgtm
