### ISSUE TITLE
Implement the Family Planning profile

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-hf#38]
![image](https://user-images.githubusercontent.com/20777928/69251083-e3ffb080-0bc1-11ea-93e4-ded620528736.png)

- [x] Back arrow or device back button takes user to the previous page they were viewing. If coming from the family profile page, the label should be "Return to family members"; if coming from the FP register list, the label should be "Return to all family planning women"
- [x] Top right 3 dots menu opens menu of options (#22 )
- [x] Take the avatar or image of the woman from their profile from their registration
- [x] Text under profile:
First Row:  {first_name} {middle_name} {surname}, {age}
Second Row: {sex} [interpunct] {village_town} [interpunct] ID: {opensrp_id}
- [x] Family planning follow-up visit button row is not generated on this profile, but will be generated when the HF is sync to server, and CHW is synced to server 

@manutarus @ellykits  We may need to add another issue to this and have a discussion around this.

- [x] Medical history row (#35 )
- [x] Family planning method row (#36)
- [x] Upcoming services row is not generated in this profile, but will be generated when the HF is sync to server, and CHW is synced to server 

@manutarus @ellykits  We may need to add another issue to this and have a discussion around this.
- [x] Family has services due/overdue row is NOT implemented on the HF
- [x] Call FAB (#37 )
- [x] Refer to facility FAB is NOT implemented on the HF
- [x] This profile should appear both from the FP register and from the All Families register and from All Client register

**Comment by allan-on** [comment]
Hi @msschroeder It isn't very clear if you, @manutarus and @ellykits discussed this point noted above 
> Upcoming services row is not generated in this profile but will be generated when the HF is sync to the server, and CHW is synced to the server

I am not sure we have the implementation to determine when CHW and HF have synced to the server so that the upcoming services row is generated. 
This also affects the item 
> Family planning follow-up visit button row is not generated on this profile but will be generated when the HF is sync to the server, and CHW is synced to the server

Kindly clarify on these

**Comment by msschroeder** [comment]
QA release Feb 17:
@allan-allay In regards to your comment: 
- [ ] Is there a way to not have the upcoming services appear? Also, the upcoming services are not being generated as expected. They are generated for children. And no all methods even generated upcoming services. I will create a separate issue just for upcoming issues.
- [ ] If the family planning row has to be generated. Then, it should be generated as it was in CHW. I will create a separate issue for this

**Comment by msschroeder** [comment]
closing as I am creating issues for the other ones.
