### ISSUE TITLE
Implement the All Families Register

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-hf#6]
Same as the [CHW All Families Register](https://github.com/OpenSRP/opensrp-client-chw/issues/8). I have copied the issue here for simplicity.

Marvel prototype: https://marvelapp.com/9j1277a/screen/48411528

<img width="353" alt="screen shot 2018-12-06 at 12 07 48 pm" src="https://user-images.githubusercontent.com/3488986/49575102-f651f180-f952-11e8-9f50-e257e2c7a7f3.png">

- [ ] Top left menu button opens side menu (#2 )
- [ ] Swiping from the left also opens side menu (#2)
- [ ] Dynamic search bar (https://github.com/OpenSRP/opensrp-client-chw-hf/issues/3)
- [ ] Please change the text in the dynamic search to read "Search name or ID"
- [ ] Due only toggle (Needs Discussion: https://github.com/OpenSRP/opensrp-client-chw-hf/issues/4)
- [ ] Row shows "{fam_name} Family" from Family Registration form
- [ ] Implement icons for each female, male child, pregnant mother, PNC mother/child, and malaria case.  Get the icons from Roger when you start on this issue. (https://github.com/OpenSRP/opensrp-client-chw-hf/issues/5)
- [ ] Where you see "Lavington #445", use the {fam_village} from the Family Registration form
- [ ] Home button at the bottom takes the user back to the main register page for whichever register they're currently in.
- [ ] Scan QR needs to be configurable - it should be an option, but has not been discussed for implementation. They have not provided the logistics for using QR codes, but it should be shown in the bottom navigation menu.
- [ ] Add family opens the add family registration form (issue to be created)

**NOTE:** There will be no visit status in this register as there is in the CHW All Families Register
