### ISSUE TITLE
Implement the family planning profile - male

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-hf#65]
![image](https://user-images.githubusercontent.com/20777928/69251083-e3ffb080-0bc1-11ea-93e4-ded620528736.png)

- [x] Back arrow or device back button takes user to the previous page they were viewing. If coming from the family profile page, the label should be "Return to family members"; if coming from the FP register list, the label should be "Return to all family planning clients"
- [x] Top right 3 dots menu opens menu of options (#22 )
- [x] Take the avatar or image of the woman from their profile from their registration
- [x] Text under profile:
First Row:  {first_name} {middle_name} {surname}, {age}
Second Row: {sex} [interpunct] {village_town} [interpunct] ID: {opensrp_id}
- [ ] Family planning follow-up visit button row is not generated on this profile, but will be generated when the HF is sync to server, and CHW is synced to server 

@manutarus @ellykits  We may need to add another issue to this and have a discussion around this.

- [x] Medical history row (#63  )
- [x] Family planning method row (#61 )
- [ ] Upcoming services row is not generated in this profile, but will be generated when the HF is sync to server, and CHW is synced to server 

@manutarus @ellykits  We may need to add another issue to this and have a discussion around this.
- [x] Family has services due/overdue row is NOT implemented on the HF
- [x] Call FAB (https://github.com/OpenSRP/opensrp-client-chw-hf/issues/64 )
- [x] Refer to facility FAB is NOT implemented on the HF
- [ ] This profile should appear both from the FP register and from the All Families register and from All Client register
