### ISSUE TITLE
Add the GPS typical locations of community responders - HF

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-hf#73]
- [x] Community responder typical locations should appear on the geowidget
- [x] GPS points will come from the community responders form based on the location hierarchy the client is associated with(https://github.com/OpenSRP/opensrp-client-chw-emergency-transport/issues/6 )
- [x] There can be up to 7 different responders, but we will only want to display those that are not empty and have a GPS collected.
 [ ] To know which responder is located where, a pop-up will appear with the responder information (#90  )
- [x] The color/icon of this point should be the same as https://github.com/OpenSRP/opensrp-client-chw-emergency-transport/issues/4
- [x] This client locations and responder information would sync from the CHW app (https://github.com/OpenSRP/opensrp-client-chw-emergency-transport/issues/8 )
